# Agenda
1. Environment
2. Numpy
3. Задачки

In [1]:
import numpy as np
import sys

Numpy - это библиотека Python, которая предоставляет поддержку многомерных массивов и высокоэффективные функции для работы с ними. Вот несколько преимуществ использования Numpy:

**Высокая производительность:** Numpy реализован на языке программирования C, что делает его очень быстрым и эффективным при выполнении операций над массивами данных. Он предоставляет возможность выполнять операции с массивами целочисленных данных гораздо быстрее, чем это было бы возможно с использованием стандартных списков Python.

**Массивы данных большого размера:** Numpy позволяет эффективно работать с многомерными массивами данных, что особенно полезно при обработке больших объемов данных в научных вычислениях, машинном обучении и других приложениях.

**Богатый функционал:** В Numpy встроено множество функций для работы с массивами, включая математические операции, логические операции, сортировку, фильтрацию, статистические операции и многое другое. Это делает работу с данными более удобной и эффективной.

**Интеграция с другими библиотеками:** Numpy является частью экосистемы Python для научных вычислений, которая включает также библиотеки как SciPy, Matplotlib, Pandas и другие. Он широко используется в научных и инженерных приложениях благодаря своей мощности и удобству использования.

**Поддержка броадкастинга:** Броадкастинг - это мощная функция Numpy, которая автоматически расширяет размеры массивов, чтобы они соответствовали друг другу при выполнении операций. Это позволяет писать более компактный и читаемый код без явного расширения массивов.

In [2]:
a = np.array(list(range(1_000_000)))
a2 = np.array(list(range(1_000_000)))

b = list(range(1_000_000))
b2 = list(range(1_000_000))

print(sys.getsizeof(a))
print(sys.getsizeof(b))

4000112
8000056


In [3]:
%timeit np.sum(a[1000:100_000])
%timeit sum(b[1000:100_000])

30.7 µs ± 993 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
2.07 ms ± 56.5 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [4]:
%timeit a * a2
%timeit [i*j for i,j in zip(b, b2)]

2.14 ms ± 107 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
105 ms ± 1.31 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


## Numpy 101

In [8]:
# создание массива
np.array([1,2,3])

array([1, 2, 3])

In [9]:
# создание массива
data = np.array([[1,2,3], [4,5,6]])

display(data)
print(data)
print([[1,2,3], [4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

[[1 2 3]
 [4 5 6]]
[[1, 2, 3], [4, 5, 6]]


In [11]:
# размерность должна быть одинаковой
np.array([[1,2,3], [4,5]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [12]:
# простые операции
display(data + 42)
display(data + data)
display(data * 3)
display(data @ data.T)

array([[43, 44, 45],
       [46, 47, 48]])

array([[ 2,  4,  6],
       [ 8, 10, 12]])

array([[ 3,  6,  9],
       [12, 15, 18]])

array([[14, 32],
       [32, 77]])

In [15]:
# размерность массива
print(data.shape)
print(data.ndim)

(2, 3)
2


In [17]:
# dtype
display(np.array([1, "1", ]))
display(np.array([1, "a", ]))
display(np.array([1, 2.5, ]))

data.dtype

array(['1', '1'], dtype='<U11')

array(['1', 'a'], dtype='<U11')

array([1. , 2.5])

dtype('int32')

In [21]:
# change type
a = np.array([1, "1"])
display(a)

display(a.astype(int))

array(['1', '1'], dtype='<U11')

array([1, 1])

In [11]:
# size
a = np.array(list(range(1_000_000)))
print(sys.getsizeof(a) / (1024*1024), a.dtype, end="\n\n")

a = np.array(list(range(1_000_000)), dtype=np.int32)
print(sys.getsizeof(a) / (1024*1024), a.dtype, end="\n\n")

a = np.array(list(range(1_000_000)), dtype=np.float16)
print(sys.getsizeof(a) / (1024*1024), a.dtype)
print(a)

7.6295013427734375 int64

3.8148040771484375 int32

1.9074554443359375 float16
[ 0.  1.  2. ... inf inf inf]


/tmp/ipykernel_5050/2491280215.py:8: RuntimeWarning: overflow encountered in cast
  a = np.array(list(range(1_000_000)), dtype=np.float16)


In [31]:
# специальные массивы
a = np.zeros((1,2,3))
display(a)
print(a.shape)

array([[[0., 0., 0.],
        [0., 0., 0.]]])

(1, 2, 3)


In [29]:
# специальные массивы
a = np.ones((3,2,1))
display(a)
print(a.shape)

array([[[1.],
        [1.]],

       [[1.],
        [1.]],

       [[1.],
        [1.]]])

(3, 2, 1)


In [33]:
# специальные массивы
a = np.empty((2,3))
display(a)
print(a.shape)

array([[0., 0., 0.],
       [0., 0., 0.]])

(2, 3)


In [36]:
# специальные массивы
a = np.full(2, fill_value=42)
display(a)
print(a.shape)

array([42, 42])

(2,)


In [37]:
# специальные массивы
a = np.identity(3)
display(a)
print(a.shape)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

(3, 3)


In [17]:
# специальные массивы
a = np.eye(3, 4)
display(a)
print(a.shape)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

(3, 4)


In [18]:
# np.arange
display(np.arange(-2.5, 1.5, 0.5))
display(np.arange(-2.5, 1.5+1e-6, 0.5))
display(np.arange(-2.5, 1.5+1e-20, 0.5))

array([-2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,  1. ])

array([-2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,  1. ,  1.5])

array([-2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,  1. ])

**функции создания массива**

|||
|---|---|
|array| копирует данные |
|asarray| не копирует данные |
|arange| аналог range, возвращает массив |
|ones, ones_like | возвращает массив из единиц, ones_like - "копирует" размероность другого массива |
|zeros, zeros_like | массив нулей |
|empty, empty_like | выделяют память под новые массивы |
|full, full_like | заполняет массив заданным значением |
|eye, identity | единичная матрица |

## Элементарные операции с массивами

In [38]:
# создадим массив
data = np.array([[1,2,3],
                 [4,5,6]])
data

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
# + - * / // % (скаляр) - применяются к каждому элементу массива
display(data + 3)
display(data - 3)
display(data * 3)
display(data / 3)
display(data // 3)
display(data % 3)

array([[4, 5, 6],
       [7, 8, 9]])

array([[-2, -1,  0],
       [ 1,  2,  3]])

array([[ 3,  6,  9],
       [12, 15, 18]])

array([[0.33333333, 0.66666667, 1.        ],
       [1.33333333, 1.66666667, 2.        ]])

array([[0, 0, 1],
       [1, 1, 2]])

array([[1, 2, 0],
       [1, 2, 0]])

In [21]:
# + - * / // % (массив) - применяется к каждой паре элементов массива
display(data + data)
display(data - data)
display(data * data)
display(data / data)
display(data // data)
display(data % data)

array([[ 2,  4,  6],
       [ 8, 10, 12]])

array([[0, 0, 0],
       [0, 0, 0]])

array([[ 1,  4,  9],
       [16, 25, 36]])

array([[1., 1., 1.],
       [1., 1., 1.]])

array([[1, 1, 1],
       [1, 1, 1]])

array([[0, 0, 0],
       [0, 0, 0]])

In [22]:
# > < >= <= !=
display(data >= 2)
display(data != 4)

array([[False,  True,  True],
       [ True,  True,  True]])

array([[ True,  True,  True],
       [False,  True,  True]])

In [23]:
# reshape
display(data.reshape(3,2))
display(data.reshape(1, -1))
display(data.flatten())
display(data.reshape(4,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

array([[1, 2, 3, 4, 5, 6]])

array([1, 2, 3, 4, 5, 6])

ValueError: cannot reshape array of size 6 into shape (4,2)

In [53]:
# slices
display(data[0, 2]) # первая строка, третий элемент
display(data[0, :]) # первая строка
display(data[:, 1]) # второй столбец
display(data[:, 1:-1]) # второй столбец

3

array([1, 2, 3])

array([2, 5])

array([[2],
       [5]])

In [54]:
# slices
arr = np.array(range(12))
arr.resize(2,2,3) # inplace
display(arr)

display(arr[:, 0, :])
display(arr[..., 0])
display(arr[..., 1])

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

array([[0, 1, 2],
       [6, 7, 8]])

array([[0, 3],
       [6, 9]])

array([[ 1,  4],
       [ 7, 10]])

## Операции с массивами

In [55]:
data

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
# как считаются статистики
display(np.apply_along_axis(np.mean, 1, data))
display(np.apply_along_axis(np.mean, 0, data))

array([2., 5.])

array([2.5, 3.5, 4.5])

In [28]:
# расчет статистик
print(np.mean(data))
print(np.median(data, axis=0))
print(np.min(data, axis=1), np.max(data))
print(np.var(data, axis=1))

3.5
[2.5 3.5 4.5]
[1 4] 6
[0.66666667 0.66666667]


In [29]:
# broadcasting
arr1 = np.array([1, 2, 3])
arr2 = np.array([[4, 5, 6],
                 [7, 8, 9]])

display(arr1 + arr2)

array([[ 5,  7,  9],
       [ 8, 10, 12]])

In [30]:
# работа с множествами
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([4, 5, 6, 7, 8])

display(np.union1d(arr1, arr2))
display(np.intersect1d(arr1, arr2))
display(np.setdiff1d(arr1, arr2))
display(np.setxor1d(arr1, arr2))

array([1, 2, 3, 4, 5, 6, 7, 8])

array([4, 5])

array([1, 2, 3])

array([1, 2, 3, 6, 7, 8])

In [60]:
# генерация случайных чисел
display(np.random.rand(2, 2))  # Случайные числа из равномерного распределения на [0, 1)
display(np.random.randint(1, 10, size=(2, 2)))  # Целые числа в диапазоне [1, 10)

array([[0.03479693, 0.31327393],
       [0.90986422, 0.08794436]])

array([[3, 9],
       [3, 1]])

In [71]:
# np.unique
arr = np.array([1,2,1,3,4,4,-1])
display(np.unique(arr))
display(np.unique(arr, return_counts=True))

array([-1,  1,  2,  3,  4])

(array([-1,  1,  2,  3,  4]), array([1, 2, 1, 1, 2], dtype=int64))

In [74]:
# np.where
display(np.where(arr >= 3))
display(np.where(arr >= 3, 42, arr))

(array([3, 4, 5], dtype=int64),)

array([ 1,  2,  1, 42, 42, 42, -1])

## Задачки

In [75]:
from typing import Union, Optional, List, Tuple

In [81]:
# Написать класс для расчета статистик
# inp: 1D Union[List[int|float], Tuple[int|float], np.ndarray[int|float]]
class Statistics:
    def __init__(self, data: Union[List[int|float], Tuple[int|float], np.ndarray[int|float]]):
        # convert 
        self.data = data
        
    def calculate_mean(self) -> float | int:
        # считаем среднюю от self.data
        raise NotImplementedError("Надо написать расчет")
        
    def calculate_median(self) -> float | int:
        # считаем медиану от self.data
        raise NotImplementedError("Надо написать расчет")
        
    def calculate_mode(self) -> float | int:
        # считаем моду от self.data
        """
        в случае если два и более объекта встречаются одинаковое количество раз
        модой будет наибольший из них
        
        Пример1:
        data = [1,2,2,3]
        out: 2
        
        Пример2:
        data = [1,2,3]
        out: 3
        """
        raise NotImplementedError("Надо написать расчет")
        
# check
obj = Statistics([1,2,3])
obj.calculate_mean()

NotImplementedError: Надо написать расчет

In [114]:
class Statistics:
    def __init__(self, data: Union[List[int|float], Tuple[int|float], np.ndarray[int|float]]):
        # convert 
        self.data = np.asarray(data)
        
    def calculate_mean(self) -> float | int:
        # считаем среднюю от self.data
        return self.data.mean()
        
    def calculate_median(self) -> float | int:
        # считаем медиану от self.data
        return np.median(self.data)
        
    def calculate_mode(self) -> float | int:
        # считаем моду от self.data
        """
        в случае если два и более объекта встречаются одинаковое количество раз
        модой будет наибольший из них
        
        Пример1:
        data = [1,2,2,3]
        out: 2
        
        Пример2:
        data = [1,2,3]
        out: 3
        """
        unique_elements, counts = np.unique(data, return_counts=True)
        max_elements_indexes = np.where(counts == counts.max())[0]
        mode = unique_elements[max_elements_indexes]
        return max(mode)
        # raise NotImplementedError("Надо написать расчет")

# check
obj = Statistics([-1,2,3,4])
print(obj.calculate_mean())
print(obj.calculate_median())
print(obj.calculate_mode())

2.0
2.5
2


In [36]:
class StatisticNew(Statistics):
    def calculate_mean(self):
#         return np.mean(self.data)
        return self.data.mean()
    
# check
obj = StatisticNew(np.array([1,2,3]))
obj.calculate_mean()

2.0

In [37]:
# check
obj = StatisticNew([1,2,3])
obj.calculate_mean()

AttributeError: 'list' object has no attribute 'mean'

**Задачки numpy**

I. Дан np.ndarray чисел, найти индексы всех максимальных элементов в массиве.

Пример:\
inp: np.asarray([1,2,3,3,2,-1])\
out: [2,3]

II. Найти второй максимальный элемент в массиве.


Пример:\
inp: np.asarray([1,2,3,3,2,-1])\
N - (2, 1_0000_000)\
out: 2


III. Даны два [1,2]-мерных массива, найдите евклидово расстояние между ними. Ответ сократите используя round до 3 знаков после запятой.

Пример1:\
inp:\
    arr1=np.asarray([1,2,3])\
    arr2=np.asarray([2,3,42])\
out: [39.025]

Пример2:\
inp:
    arr1 = np.array([[1, 2], [3, 4], [5, 6]])\
    arr2 = np.array([[2, 3], [4, 5], [6, 7]])\
out: [1.41421356, 1.41421356, 1.41421356]

In [181]:
# Дан np.ndarray чисел, найти индексы всех максимальных элементов в массиве.
def task1(arr: np.ndarray):
    max_element = arr.max()
    return np.where(arr == max_element)[0]

task1(np.asarray([42,1,2,42,]))

array([0, 3], dtype=int64)

In [185]:
# Найти второй максимальный элемент в массиве.
def task2(arr: np.ndarray):
    max_element = arr.max()
    arr = arr[np.where(arr != max_element)]
    return arr.max()

task2(np.asarray([1,2,1,1,1,2,42,-1]))

2

In [189]:
# Даны два [1,2]-мерных массива, найдите евклидово расстояние между ними.
# Если размерность массива равна двум - надо найти евклидово расстояние между каждой строкой
# Строка - первая размерность
# Ответ сократите используя round до 3 знаков после запятой.
def task3(arr1: np.ndarray, arr2: np.ndarray):
    if arr1.ndim == 2:
        return np.sqrt(np.sum((arr1 - arr2) ** 2, axis=1))
    else:
        return np.sqrt(np.sum((arr1 - arr2)**2))

print(task3(np.asarray([1,2,3]), np.asarray([2,3,42])))

arr1 = np.array([[1, 2], [3, 4], [5, 6]])
arr2 = np.array([[2, 3], [14, 5], [6, 42]])
print(task3(arr1, arr2))

39.02563260217571
[ 1.41421356 11.04536102 36.01388621]


**Задачки на программирование**

I. Дан список чисел, найти два максимальных числа

Пример:\
inp: [1,2,4,4,2,-1]\
out: [2,4]

II. Дан список чисел, найти сколько элементов списка строго больше обоих своих соседей

Пример1:\
inp: [1,2,3,4,5]\
out: 0

Пример2:
inp: [1,42,3,42,5]\
out: 2

III. На вход подается список чисел и какое-то число, найдите элемент массива, максимально близкий к этому числу.

Пример1:\
inp: data=[1,2,3,4,5], k=3\
out: 3

Пример2:\
inp: data=[1,2,3,4,5], k=100\
out: 5

IV. На вход подается список чисел, вывести его кумулятивную сумму:

Пример:\
inp: data=[1,2,3,4,5]\
out: [1,3,6,10,15]

In [193]:
"""
I. Дан список чисел, найти два максимальных числа

Пример:
inp: [1,2,4,4,2,-1]
out: [2,4]
"""
def task1(data: list) -> list:
    data_unique = set(data)
    data_sorted = sorted(data_unique)
    return data_sorted[-2:]

task1([1,2,3,4,5,6])

[5, 6]

In [197]:
"""
II. Дан список чисел, найти сколько элементов списка строго больше обоих своих соседей

Пример1:
inp: [1,2,3,4,5]
out: 0

Пример2: inp: [1,42,3,14,5]
out: 2
"""
def task2(data: list) -> int:
    res = 0
    for idx in range(1, len(data)-1):
        if data[idx] > data[idx-1] and data[idx] > data[idx+1]:
            res += 1
    return res

print(task2([1,2,3,4,5]))
print(task2([1,42,3,14,5,500]))

0
2


In [204]:
"""
III. На вход подается список чисел и какое-то число, найдите элемент массива, максимально близкий к этому числу.

Пример1:
inp: data=[1,2,3,4,5], k=3
out: 3

Пример2:
inp: data=[1,2,3,4,5], k=100
out: 5

Пример3:
inp: data=[1,2,-3,4,5], k=-2
out: -3
"""
def task3(data: List[int|float], k=int|float) -> int|float:
    res = float("inf")
    val = data[0]
    for i in data:
        diff = abs(i - k)
        if diff < res:
            val = i
            res = diff
    return val        
    
print(task3(data=[1,2,-3,4,5], k=-2))
print(task3(data=[1,2,3,4,5], k=100))

-3
5


In [213]:
"""
IV. На вход подается список чисел, вывести его кумулятивную сумму:

Пример:
inp: data=[1,2,3,4,5]
out:      [1,3,6,10,15]
# 1 [1,2,3,4,5]
# 2 [1,3,3,4,5]
# 3 [1,3,6,4,5]
# 4 [1,3,6,10,5]
# 5 [1,3,6,10,15]
"""
def task4(data: list) -> list:
    for idx in range(1, len(data)):
        data[idx] = data[idx-1] + data[idx]
    return data

display(task4([1,2,3,4,5]))
display(task4([-15,1,2,3,4,5]))
display(task4([1]))
display(task4([]))

[1, 3, 6, 10, 15]

[-15, -14, -12, -9, -5, 0]

[1]

[]